name: Release to npm
on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: "actions/setup-node@v3"
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: false

      - name: "Install Packages"
        run: pnpm i --frozen-lockfile

      - name: "Build"
        run: pnpm run build

      - name: Publish to npm
        run: npx lerna publish --no-private from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
